name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Navigate to project directory
            cd ~/project/ReBridge
            
            # Pull latest changes
            git pull origin main
            
            # Install dependencies
            pnpm install --frozen-lockfile
            
            # Build the project
            pnpm run build
            
            # Run database migrations
            cd apps/web
            npx prisma generate
            npx prisma migrate deploy
            cd ../..
            
            # Restart services using PM2
            pm2 restart ecosystem.config.prod.js --update-env || pm2 start ecosystem.config.prod.js
            
            # Verify services are running
            pm2 status
            
            echo "Deployment completed successfully!"